# Generated by Django 5.1.1 on 2024-09-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название документа"),
                ),
                ("file", models.FileField(upload_to="documents/", verbose_name="Файл")),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "pages",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество страниц"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrinterStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paper_amount",
                    models.PositiveIntegerField(
                        default=100, verbose_name="Количество бумаги (листов)"
                    ),
                ),
            ],
        ),
    ]
