# Generated by Django 5.1.5 on 2025-02-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document_price_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='img1',
            field=models.ImageField(blank=True, upload_to='terminal_img', verbose_name='первое изображение'),
        ),
    ]
