# Generated by Django 5.1.5 on 2025-03-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_printer_img1'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Сервер активен?'),
        ),
        migrations.AddField(
            model_name='terminal',
            name='ngrok_url',
            field=models.URLField(blank=True, null=True, verbose_name='Текущий URL `ngrok`'),
        ),
    ]
