# Generated by Django 5.1.5 on 2025-03-15 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_terminal_is_active_terminal_ngrok_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('file', models.FileField(upload_to='templates/', verbose_name='Файл шаблона')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('paper_count', models.PositiveIntegerField(default=100, verbose_name='лист')),
            ],
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('paid', 'Оплачен'), ('printed', 'Распечатан')], default='pending', max_length=50, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.terminal', verbose_name='Терминал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.templatedocument', verbose_name='Документ')),
            ],
        ),
    ]
