# Generated by Django 5.1.5 on 2025-03-23 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_templatedocument_printjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatedocument',
            name='paper_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество страниц'),
        ),
        migrations.CreateModel(
            name='TemplateDocumentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название группы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('parent_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='core.templatedocumentgroup', verbose_name='Родительская группа')),
            ],
        ),
        migrations.AddField(
            model_name='templatedocument',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.templatedocumentgroup', verbose_name='Группа'),
        ),
    ]
