# Generated by Django 5.1.5 on 2025-03-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_templatedocument_paper_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatedocument',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='template_previews/', verbose_name='Превью документа'),
        ),
    ]
