# Generated by Django 5.1.5 on 2025-04-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_printer_latitude_printer_location_printer_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='last_ping',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
