# Generated by Django 5.1.5 on 2025-04-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_terminal_last_ping'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_duplex',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Цветная печать'),
        ),
    ]
